/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_olfillasodikno_libenet_Enet */

#ifndef _Included_de_olfillasodikno_libenet_Enet
#define _Included_de_olfillasodikno_libenet_Enet
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     de_olfillasodikno_libenet_Enet
 * Method:    enet_initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_olfillasodikno_libenet_Enet_enet_1initialize
  (JNIEnv *, jclass);

/*
 * Class:     de_olfillasodikno_libenet_Enet
 * Method:    enet_deinitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_olfillasodikno_libenet_Enet_enet_1deinitialize
  (JNIEnv *, jclass);

/*
 * Class:     de_olfillasodikno_libenet_Enet
 * Method:    enet_host_create
 * Signature: (JLjava/lang/String;SIIII)J
 */
JNIEXPORT jlong JNICALL Java_de_olfillasodikno_libenet_Enet_enet_1host_1create
  (JNIEnv *, jclass, jstring, jshort, jint, jint, jint, jint);

/*
 * Class:     de_olfillasodikno_libenet_Enet
 * Method:    enet_host_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_olfillasodikno_libenet_Enet_enet_1host_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_olfillasodikno_libenet_Enet
 * Method:    connect
 * Signature: (JLjava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_de_olfillasodikno_libenet_Enet_connect
  (JNIEnv *, jclass, jlong, jstring, jint, jint);

/*
 * Class:     de_olfillasodikno_libenet_Enet
 * Method:    enet_host_service
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_de_olfillasodikno_libenet_Enet_enet_1host_1service
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     de_olfillasodikno_libenet_Enet
 * Method:    getEvent
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_olfillasodikno_libenet_Enet_getEvent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_olfillasodikno_libenet_Enet
 * Method:    enet_packet_create
 * Signature: ([BII)J
 */
JNIEXPORT jlong JNICALL Java_de_olfillasodikno_libenet_Enet_enet_1packet_1create
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     de_olfillasodikno_libenet_Enet
 * Method:    enet_packet_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_olfillasodikno_libenet_Enet_enet_1packet_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_olfillasodikno_libenet_Enet
 * Method:    enet_peer_send
 * Signature: (JCJ)V
 */
JNIEXPORT void JNICALL Java_de_olfillasodikno_libenet_Enet_enet_1peer_1send
  (JNIEnv *, jclass, jlong, jchar, jlong);

/*
 * Class:     de_olfillasodikno_libenet_Enet
 * Method:    enet_host_flush
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_olfillasodikno_libenet_Enet_enet_1host_1flush
  (JNIEnv *, jclass, jlong);

/*
 * Class:     de_olfillasodikno_libenet_Enet
 * Method:    enet_host_broadcast
 * Signature: (JCJ)V
 */
JNIEXPORT void JNICALL Java_de_olfillasodikno_libenet_Enet_enet_1host_1broadcast
  (JNIEnv *, jclass, jlong, jchar, jlong);

/*
* Class:     de_olfillasodikno_libenet_Enet
* Method:    getAddress
* Signature: (J)[B
*/
JNIEXPORT jbyteArray JNICALL Java_de_olfillasodikno_libenet_Enet_getAddress
(JNIEnv *, jclass, jlong);


JNIEXPORT void JNICALL Java_de_olfillasodikno_libenet_Enet_enet_1peer_1destroy
(JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
